### ISSUE TITLE
No Travis integration

### ISSUE THREAD

**Issue by willemstuursma** [mollie/wix-paid-membership#1]
Hi @hbierlee.

I noticed that there is no travis integration.

Could you add this for us:

* Add some linting (not sure how this works with node) for all supported node versiosn
* Execute the tests
* Maybe some style checks, if you want / have these already.

**Comment by hbierlee** [comment]
I'll look into this over the weekend!

**Comment by hbierlee** [comment]
I integrated travis with the following features:

- linting and style checks via the eslint package, according to the [standard](https://github.com/standard/standard) rule set
- any unit tests are run automatically, but I let it skip my most important unit test because there's manual component to it: I have to 'pay' the test payments in my browser by pressing the 'paid' status. I'd be very curious if there's a way around this and how you handle this at mollie! I already mailed your customer support about this once, and they said it was not possible to automate paying test payments.

Anyway, I hope this is a good enough CI pipeline for the purposes of this project. Otherwise, feel free to re-open this issue.

**Comment by willemstuursma** [comment]
> I have to 'pay' the test payments in my browser by pressing the 'paid' status. 

We would handle this by using a mock so no actual interaction is necessary.

**Comment by willemstuursma** [comment]
> Anyway, I hope this is a good enough CI pipeline for the purposes of this project. Otherwise, feel free to re-open this issue.

Its great to have a start, thanks. We can always improve it later with new issues.

**Comment by hbierlee** [comment]
> We would handle this by using a mock so no actual interaction is necessary.

@willemstuursma Great advice, I spend today adding this. The 'integration' tests that use the mollie API now all have a 'unit' test counter-parts where the exact same is tested, but mollie API is mocked. It also helped me find a potential bug.
